### ISSUE TITLE
Not compiling when using arduino motor shield

### ISSUE THREAD

**Issue by Ge0rges** [miguelgrinberg/michelino#1]
Hi!

First of all I'd like to thank you for open sourcing such clean and useful code! Unfortunately when trying to compile with the `#define ENABLE_ARDUINO_MOTOR_DRIVER` the compiler gives out an error here         `Motor leftMotor;` because Motor isn't defined type. Any ideas?

**Comment by miguelgrinberg** [comment]
Do you have the `arduino_motor_driver.h` header file in the same directory as the ino file?

**Comment by Ge0rges** [comment]
Yes

**Comment by miguelgrinberg** [comment]
Show me the complete compiler log, please.

**Comment by Ge0rges** [comment]
I fixed it by updating to the latest arduino IDE version. Thanks for all the help! Sorry I bothered you.
